### ISSUE TITLE
Imports are always moved to top of the file

### ISSUE THREAD

**Issue by Tadaboody** [hhatto/autopep8#459] opened 2018-12-13 09:00 UTC
Running autopep8 on 
```py
"""Module docstring"""
a = 5
import random
import itertools
```
results in 
```py
import itertools
import random
"""module docstring"""
a = 5
```
Instead of 
```py
"""module docstring"""
import itertools
import random
a = 5
```

**Comment by Hanaasagi** [comment] 2019-01-02 14:41
@Tadaboody. emm, I meet the same problem. Maybe this patch can solve that imports are moved above `from __future__ import` 

```Python
def get_module_imports_on_top_of_file(source, import_line_index):
    """return import or from keyword position

    example:
      > 0: import sys
        1: import os
        2:
        3: def function():
    """
    def is_string_literal(line):
        if line[0] in 'uUbB':
            line = line[1:]
        if line and line[0] in 'rR':
            line = line[1:]
        return line and (line[0] == '"' or line[0] == "'")

    def is_future_import(line):
        nodes = ast.parse(line)
        for node in nodes.body:
            if isinstance(node, ast.ImportFrom) and node.module == '__future__':
                return True
        return False

    allowed_try_keywords = ('try', 'except', 'else', 'finally')
    for cnt, line in enumerate(source):
        if not line.rstrip():
            continue
        elif line.startswith('#'):
            continue
        if line.startswith('import ') or line.startswith('from '):
            if cnt == import_line_index or is_future_import(line):
                continue
            return cnt
        elif pycodestyle.DUNDER_REGEX.match(line):
            continue
        elif any(line.startswith(kw) for kw in allowed_try_keywords):
            continue
        elif is_string_literal(line):
            return cnt
        else:
            return cnt
    return 0
```

It adapts to following situation

```Python
import math
a = 1
import collections
from __future__ import print_function
import functools
```

But it can't solve that

```Python
import collections
from __future__ import print_function
a = 1
```

Because, the above code will pass the check of `pycodestyle`. It only checks `E402`(`Module level import not at top of file`), but `pyflakes` contains additional check  `F404`(`from __future__ imports must occur at the beginning of the file`)

By the way, I think PEP8 is just code style, not a lint. It considers that the problem is not caused by `autopep8`, actually it's not a tool to fix `SyntaxError`.

Reference [Flake8Rules](https://lintlyci.github.io/Flake8Rules/)

**Comment by Tadaboody** [comment] 2019-01-02 17:14
@Hanaasagi Will it fix the case of turning
```py
from __future__ import print_function
print(3)
import functools
print(4)
```
into
```py
import functools
from __future__ import print_function
print(3)
print(4)
```
Thus _creating_ a syntax error by using `autopep8`?

**Comment by Hanaasagi** [comment] 2019-01-03 01:43
I think so. `autopep8` depends on `pycodestyle`, above code will report that
```
t.py:3:1: E402 module level import not at top of file
```
And this patch using `ast` module to check whether the target line contains a `__future__` import. if has, it will insert to next suitable position.

**Comment by waspinator** [comment] 2019-01-03 21:40
imports are also moved above `sys.path.insert()`, which breaks the import statement.

**Comment by hhatto** [comment] 2019-01-12 01:42
It is resolved in this issue:
- [ ] Change the import statement that it does not moved above the module document by E402
- [x] Change the import statement that it does not moved above the `from __future__ import XX` by E402 ( Thanks @Hanaasagi )

**Comment by Hanaasagi** [comment] 2019-01-13 05:02
I'd like to resolve the remianing issue.

**Comment by Hanaasagi** [comment] 2019-01-13 06:36
#467

**Closed** 2019-01-13 13:48 UTC
