### ISSUE TITLE
Incorrect handling of variables ending with '_'

### ISSUE THREAD

**Issue by tomsib2001** [hhatto/autopep8#670] opened 2023-02-01 13:33 UTC
---

`x_ : str` in a function argument gets reformatted as `x_: str` which then triggers a runtime error `SyntaxError: invalid syntax`

## Python Code
```python
def f(x_ : str):
    return x_
```

## Command Line and Configuration
No specific configuration
`.pep8`, `setup.cfg`, ...
```ini
[pep8]

```

Command Line
```shell
$ autopep8 -i file.py 
```

## Your Environment
* Python version: Python 3.10.6
* autopep8 version: autopep8 2.0.0 (pycodestyle: 2.10.0)
* Platform: Linux Ubuntu 22.04

**Comment by nbaju1** [comment] 2023-02-15 13:26
Are you saying that running code with a function defined as

```python
def f(x_: str):
    return x_
```
procude that error? Or the actual formatting of the function argument? Cause I have not issues running a script with this syntax (on 3.10.8 though).

**Comment by hhatto** [comment] 2023-03-04 02:55
I can't reproduce it specifically in my environment.

```
$ python3 --version
Python 3.10.6

$ autopep8 --version
autopep8 2.0.0 (pycodestyle: 2.10.0)

$ cat ff.py
def f(x_ : str):
    return x_

$ autopep8 -d ff.py
--- original/ff.py
+++ fixed/ff.py
@@ -1,2 +1,2 @@
-def f(x_ : str):
+def f(x_: str):
     return x_

$ autopep8 -i ff.py

$ python ff.py

$
```

Is it possible that file.py is importing another file and a syntax error is occurring there?
In any case, it is not autopep8's problem for now, so I'll close it.
If you have additional information, I would appreciate your comments.

@tomsib2001

**Closed by hhatto** 2023-03-04 02:55 UTC
